### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by josefdolezal** [florianmari/LiveGQL#1]
Hey @florianmari! I love the idea of combining sockets and GraphQL. Would you consider adding support for [Carthage](https://github.com/Carthage/Carthage) dependency manager? It would be super-cool to have it as option.

It only requires to have library `.xcodeproj` in the repository with shared schemes for all supported platforms.

If you are interested, I can make PR.

**Comment by florianmari** [comment]
Hello, 

It would be super if you can make PR to support Carthage dependency manager!

Thank you!
