### ISSUE TITLE
Add support for payload on init

### ISSUE THREAD

**Issue by sciutand** [florianmari/LiveGQL#3]
When connecting to a socket often we need to have some sort of authentication. The javascript client allows for connection parameters to be sent over to perform authentication.
http://dev.apollodata.com/tools/graphql-subscriptions/authentication.html

I think it would be good if the iOS client would allow similar option. Send payload in `initServer` function?

**Comment by florianmari** [comment]
Hello,

Thank you for theses informations, of course it would be good to have this option! I'm gonna improve the library by the end of week and hopefully integrate this option in the next update around next week!

Cheers

**Comment by florianmari** [comment]
Hello, @sciutand I'm working on a new update so this feature will be available next week 👍
