### ISSUE TITLE
Redefinition of Starscream modulemaps

### ISSUE THREAD

**Issue by rhishikeshj** [florianmari/LiveGQL#6]
Hi,
So I am trying to link the LiveGQL framework with the Example project and not using the Cocoapod.
Now since LiveGQL only links with Starscream, if I do not include starscream separately in the Example application, it crashes at run time saying Starscream not found.

But if I do include Starscream via the Pods project, I get a compilation error :

`/Users/mjolnir/workspace/referron/LiveGQL/Example/Pods/Starscream/zlib/module.modulemap:1:8: error: redefinition of module 'SSCZLib'
module SSCZLib [system] {
       ^
/Users/mjolnir/workspace/referron/LiveGQL/Carthage/Checkouts/Starscream/zlib/module.modulemap:1:8: note: previously defined here
module SSCZLib [system] {
       ^
/Users/mjolnir/workspace/referron/LiveGQL/Example/Pods/Starscream/zlib/module.modulemap:6:8: error: redefinition of module 'SSCommonCrypto'
module SSCommonCrypto [system] {
       ^
/Users/mjolnir/workspace/referron/LiveGQL/Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: note: previously defined here
module SSCommonCrypto [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Starscream'`

So somehow, LiveGQL ends up including the modulemap for Starscream too which causes problems if we include Starscream with the Application project also.

Can you please help with what might be missing in the setup ? Or do we need to make changes in the LiveGQL project ?

Essentially, I need to be able to link the LiveGQL framework directly with my application and make it work.

**Comment by florianmari** [comment]
Interesting point... I didn't think about dependencies like that with Pod, I will update very soon the library with a fix for a manual install.

Maybe I'm gonna give up Starscream and use SocketRocket by Facebook. In all cases, one of those will be integrated in LiveGQL and won't be used a Pod reference

**Comment by rhishikeshj** [comment]
Thanks for taking this up !
I do have a question regarding this, if you could help me out.

Why does the LiveGQL framework bring in the Starscream modulemap files ? Even if I just link to the Starscream framework and not actually include it in the Build phases for the LiveGQL framework project ?

Also, if there are simple steps which you know will work, please let me know. I am willing to take the time to fix this. I want to make some changes to the code for my usage.

**Comment by rhishikeshj** [comment]
Hey, so I made the changes that you suggested.
I think the issue is with [Starscream](https://github.com/daltoniam/Starscream/issues/361) but there is no input from them yet which is problematic for me.

So I forked and [created a branch](https://github.com/referron/LiveGQL/tree/feature/migrate-to-socketrocket) with all the changes. 

My setup now seems to be working so now I have a library which I can update and use in my app :)
Let me know if you want to open a pull request and integrate these changes into your code.
Also, if you find any issues with the code, do let me know so that I can improve quality.

**Comment by florianmari** [comment]
Hello!

Thank for all your investment in the project and happy it works now, I saw your branch but not reviewed yet, but it would be cool if you make a PR, I will check it this week end!

Cheers!

**Comment by florianmari** [comment]
Hey @rhishikeshj 

I looked over your contribution and it is so cool for the future of LiveGQL i'm working on. Is it possible to make a PR into the "develop" branch? I'm gonna release a new version by the end of January

Thank you!

**Comment by florianmari** [comment]
Merged and released
